### ISSUE TITLE
flutter SDK更新到1.7.8以后Action识别不了，希望解决一下

### ISSUE THREAD

**Issue by lishoujieA** [alibaba/fish-redux#369] opened 2019-07-09 07:39 UTC
**Describe the bug**
Show the code you wrote as completely as possible.
```dart
/// your code here
``` 

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
1. The version of fish-redux which you are using.
2. The information from flutter doctor.

**Comment by zjuwjf** [comment] 2019-07-09 08:01
Duplicate of #303

**Closed by zjuwjf** 2019-07-09 08:01 UTC
