### ISSUE TITLE
effect.dart 错误

### ISSUE THREAD

**Issue by xiong425** [alibaba/fish-redux#309] opened 2019-06-14 01:14 UTC
我之前按照example中的例子写的代码运行正常，代昨天升级了到flutter 1.7.6, fish redux 0.2.2, 则出现了下面的错误

`
Effect<ReportListState> buildEffect() {
  return combineEffects(<Object, Effect<ReportListState>>{
    Lifecycle.initState: _init,
    ReportListAction.load: _load,
    ReportListAction.onEditReport: _onEditReport,
    ReportListAction.onDeleteReport: _onDeleteReport,
  });
}
`

error: The function '_init' has type 'void Function(Action, Context<ReportEditState>)' that isn't of expected type 'dynamic Function(dynamic, Context<ReportEditState>)'. This means its parameter or return type does not match what is expected. (strong_mode_invalid_cast_function at lib/screens/reports/edit_page/effect.dart:14)

**Comment by zjuwjf** [comment] 2019-06-14 01:30
Duplicate of #303

**Closed by zjuwjf** 2019-06-14 01:30 UTC
