### ISSUE TITLE
Effect 里面的事件处理 提示参数不匹配

### ISSUE THREAD

**Issue by dyzyang** [alibaba/fish-redux#342] opened 2019-06-26 16:14 UTC
```
Flutter 1.7.10-pre.19 • channel master • https://github.com/flutter/flutter.git
Framework • revision 305a99501e (18 hours ago) • 2019-06-25 18:20:39 -0400
Engine • revision 107fe82343
Tools • Dart 2.4.0
```

`The function '_onLogin' has type 'void Function(Action, Context<LoginState>)' that isn't of expected type 'void Function(dynamic, Context<LoginState>)'. This means its parameter or return type does not match what is expected.`

![image](https://user-images.githubusercontent.com/51750139/60196530-f32b3e00-986f-11e9-9f56-e2b4b4361ec5.png)

**Comment by dyzyang** [comment] 2019-06-26 16:26
![image](https://user-images.githubusercontent.com/51750139/60197553-2c64ad80-9872-11e9-9c5e-ecf3a0d3222f.png)

**Comment by zjuwjf** [comment] 2019-06-27 02:09
Duplicate of #303

**Comment by dyzyang** [comment] 2019-06-27 02:19
目前的问题是 
The function '_onLogin' has type **'void Function(Action, Context<LoginState>)'**
 that isn't of expected type **'void Function(dynamic, Context<LoginState>)'**. 

This means its parameter or return type does not match what is expected.

`Duplicate of #303`
我使用的 **widgets.dart hide Action** 才会提示这个问题，如果我不使用 **hide action** 就会出现跟 #303 一样的问题

**Closed** 2019-07-01 13:08 UTC
