### ISSUE TITLE
beta 1.17.版本Page类名冲突

### ISSUE THREAD

**Issue by SystemTce** [alibaba/fish-redux#641] opened 2020-04-09 02:37 UTC
问题：
![image](https://user-images.githubusercontent.com/27715452/78852078-00f02f80-7a4e-11ea-9cf0-e270d7fb91fe.png)

环境：
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (2 days ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

**Comment by SystemTce** [comment] 2020-04-09 02:52
https://github.com/SystemTce/fish-redux
自己维护吧～，官方可能不维护了

**Comment by zjuwjf** [comment] 2020-04-10 05:00
Duplicate of #638

**Closed by zjuwjf** 2020-04-10 05:00 UTC
